apiVersion: v1
kind: Pod
metadata:
  name: ids
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "ovs-conf" }, { "name": "ovs-conf" }]'
spec:
  nodeName: worker1  # Specify the node name here
  containers:
  - name: ids
    image: alpine
    command: ["/bin/sh", "-c", "while true; do sleep 1000; done"]
    securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
    resources:
      limits:
        ovs-cni.network.kubevirt.io/br1: 2

